# -*- coding: utf-8 -*-
"""T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i76z63SqdHZVaMmUSo1tgOmNpOc99GMr
"""

from google.colab import drive
drive.mount('/content/drive')

"""#  Install required packages"""

!pip install simplet5

"""# Import libraries"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split

"""# Import SimpleT5"""

from simplet5 import SimpleT5

"""#  Read the CSV file from your local directory
# Upload your CSV file to Google Colab and update the file path
"""

df = pd.read_csv("/content/drive/MyDrive/summary/news_summary.csv", encoding='latin-1', usecols=['headlines', 'text'])
df.head()

"""# Rename columns and select required columns"""

df = df.rename(columns={"headlines":"target_text", "text":"source_text"})
df = df[['source_text', 'target_text']]
df.head()

"""# Add prefix for summarization task"""

df['source_text'] = "summarize: " + df['source_text']
df.head()

"""# Split the dataset into train and test"""

train_df, test_df = train_test_split(df, test_size=0.3)
train_df.shape, test_df.shape

"""# Initialize and train the SimpleT5 model"""

model = SimpleT5()
model.from_pretrained(model_type="t5", model_name="t5-base")

from google.colab import drive
drive.mount('/content/drive')

# Your existing code for training
model.train(
    train_df=train_df[:5000],
    eval_df=test_df[:100],
    source_max_token_len=300,
    target_max_token_len=100,
    batch_size=8,
    max_epochs=3,
    use_gpu=True
)

# Assuming `model` has a save method. Adjust the method and path according to your specific library/model
model_save_path = '/content/drive/MyDrive/Project_model'
model.save(model_save_path)

from google.colab import drive
import shutil

# Mount Google Drive
drive.mount('/content/drive')

# Specify source and destination paths
source_path = '/content/outputs/simplet5-epoch-2-train-loss-0.9206-val-loss-1.3764'
destination_path = '/content/drive/MyDrive/Project_model/simplet5-epoch-2-train-loss-0.9206-val-loss-1.3764'

# Copy files to Google Drive
shutil.copytree(source_path, destination_path)

print("Model saved to Google Drive at:", destination_path)

"""# Load the trained model from the saved location"""

# Import SimpleT5
from simplet5 import SimpleT5

# Initialize the SimpleT5 model
model = SimpleT5()

# Load the trained model from the saved location
model.load_model("t5", "/content/drive/MyDrive/Project_model/simplet5-epoch-2-train-loss-0.9206-val-loss-1.3764", use_gpu=True)

# Define the text to summarize
text_to_summarize = """
Twitter’s interim resident grievance officer for India has stepped down, leaving the micro-blogging site without a grievance official as mandated by the new IT rules to address complaints from Indian subscribers, according to a source.

The source said that Dharmendra Chatur, who was recently appointed as interim resident grievance officer for India by Twitter, has quit from the post.

The social media company’s website no longer displays his name, as required under Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules 2021.

Twitter declined to comment on the development.

The development comes at a time when the micro-blogging platform has been engaged in a tussle with the Indian government over the new social media rules. The government has slammed Twitter for deliberate defiance and failure to comply with the country’s new IT rules.
"""

# Make the prediction (summarize)
summary = model.predict(text_to_summarize)

# Print the generated summary
print("Generated Summary:", summary)

